# Name of the workflow
name: Production Deploy

#Trigger the workflow on push to the main branch
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            # 取得程式碼
            - name: Checkout code
              uses: actions/checkout@v3
            # 設定Node.js
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            # 安裝依賴
            - name: Install dependencies
              run: npm install
            # 建置專案
            - name: Build project
              run: npm run build
