# Name of the workflow
name: Production Deploy

#Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # 權限設定
    permissions:
      contents: write
    steps:
      # 取得程式碼
      - name: Checkout code
        uses: actions/checkout@v3
      # 設定Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      # 安裝依賴
      - name: Install dependencies
        run: npm install
      # 執行linting
      - name: Run linter
        run: npm run lint
      # 執行測試
      - name: Run tests
        run: npm test -- --run
      # 建置專案
      - name: Build project
        run: npm run build
      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
